### ISSUE TITLE
Custom http.Client

### ISSUE THREAD

**Issue by imtaco-lh** [tuputech/tupu-go-sdk#2]
Each Handler. Perform() call will create a new http.Client instance without options, but
1. Each golang http.Client maintains an idle connection pool for reuse. Always using new client will lead to connection leak problem.
2. Callers unable to set their preferred timeout duration or other http.Client options.

So how about adding a new factory function `NewHandlerWithClient(pkey string, client *http.Client)` (original factory functions use http.DefaultClient)
or adding another method `SetClient(*http.Client)` to Handler ?

**Comment by nickeljew** [comment]
thx for your good advice.

**Comment by nickeljew** [comment]
Updated.

Example:
``` 
	tr := &http.Transport{
		MaxIdleConns:       10,
		IdleConnTimeout:    30 * time.Second,
		DisableCompression: true,
	}
	handler.Client = &http.Client{Transport: tr}
```

**Comment by imtaco-lh** [comment]
thx~
